Add options to drain command, and force reboot
weaveworks/kured pull request #109
Opened 2020-02-13 21:12 UTC by timothyrr

We have encountered scenarios in our environment where the reboot never happens due to hanging pods or a misconfigured PDB that does not allow a reboot. This adds a new option to kured: `--drain-grace-period` which gets used with the drain command as: `--grace-period`

There are also 2 new `--force-reboot` and `--force-drain` options to the kured command. `force-reboot` will tell kured whether to force it to reboot after a specified timeout no matter the status of the drain command.  `--force-drain` is the same old `--force` option that gets passed to the drain command, but now you can choose whether to enable or disable that option (previously it was always enabled).

2020-02-14 08:20 UTC, dholbach commented
@bboreham As you had a comment on #79 - how do you feel about this solution?

2020-03-09 14:58 UTC, dholbach commented
Just a quick PSA from me:

- we're hanging out in #kured on Slack
- we're planning a contributors meeting soon: here's the [link to the doodle](https://doodle.com/poll/tuwg4w4mxbbknhe3) to find a good time - be sure to pick your timezone before submitting ([preliminary agenda](https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit#))

We'd love to see you there.

2020-04-10 20:24 UTC, andrsp commented
It would be nice to have it merged and released :)

2020-07-13 00:02 UTC, sebikul commented
Would it be possible to also include a fix to issue https://github.com/weaveworks/kured/issues/121 in this PR. We are hitting a race condition with our Load Balancer draining the requests from the node, but it rebooting too fast for this process to finish.

I'm not a Go programmer, but if someone could review my code I'm more than happy to try to implement this, and whatever is needed to merge this PR.

2020-07-13 16:14 UTC, timothyrr commented
I am going to work on the fixes mentioned by @bboreham this week. I can look at that #121 issue as well. I think that should be easy enough to add in.

2020-07-14 23:20 UTC, timothyrr commented on cmd/kured/main.go
> +	    select {
@bboreham can you clarify what you mean by this exactly? I am not sure if I completely follow what should be moving with the timeouts? I have been following timeout examples I have seen here: https://gobyexample.com/timeouts

2020-08-06 19:32 UTC, timothyrr commented on cmd/kured/main.go
> +	    select {
@bboreham can you take another look? I believe it is now a bit more simplified without having 2 selects. Not sure if this is along the lines of what you were thinking or not.

2020-11-25 10:41 UTC, dholbach commented
We recently put in https://github.com/weaveworks/kured/commit/1ba3acab98fa217ea65405640706c55c89be956d so it should be easier to implement now?

2020-11-25 10:44 UTC, dholbach requested changes
Needs work after https://github.com/weaveworks/kured/commit/1ba3acab98fa217ea65405640706c55c89be956d and #210

2021-01-26 15:29 UTC, timothyrr commented
I am working on this now and will hopefully have changes made by early next week.

2021-04-06 10:08 UTC, closed without merging

2021-04-06 10:12 UTC, dholbach commented
Sorry. Can you please retarget your branch to be merged into `main` please?