Refactor reboot blocks
weaveworks/kured pull request #260
Opened 2020-12-01 16:17 UTC by evrardjp

Without this patch, we rely on global state in many functions for
which we check the reboot blockers.

This is a problem, as it's harder to test.

This patch fixes it by refactoring the reboot blockers. This also
includes a first series of unit tests for our main.

2020-12-01 16:19 UTC, evrardjp commented
This has not been tested in a cluster yet.

There are more urgent PRs to merge before this one, but I think it's worth implementing, to increase our coverage.

2021-01-14 08:52 UTC, evrardjp commented
I have rebased this one.

Now that 1.6.0 is out, it's time to give it a go.

2021-01-14 08:59 UTC, evrardjp commented
Wrongly rebased, now better.

2021-02-05 14:12 UTC, kingdonb commented
I saw you added some go tests, I was able to get this and #297 to compile and show that tests are passing (of course this only works on Linux)

Do you think the tests should be added to CI with this merge?

2021-02-05 14:25 UTC, kingdonb requested changes
There is a typo in the comment on line 188 ("lised") otherwise LGTM

2021-02-05 14:25 UTC, kingdonb commented on cmd/kured/main.go
> +	// lised used to filter pods (podSelector)
"lised" here should read, list?

2021-02-05 15:27 UTC, evrardjp commented
@kingdonb CI is already doing compiling and lint tests, so I don't think there is something extra to add. But I may be wrong, it's been a while I touched the CI...

2021-02-05 17:00 UTC, kingdonb commented
The unit test file main_test.go that you added is new, I don't see any others like it in this repo. I wouldn't expect CI to know to run `go test` if it isn't invoked in the Makefile or Dockerfile, but I'm open to being shown something if you know more about this (I myself am new here, too!)

2021-03-22 14:22 UTC, evrardjp commented
Abandonned: Superseded by https://github.com/weaveworks/kured/pull/297

2021-03-22 14:22 UTC, closed without merging